=== kang-lee-lab/lab-surveys/App/static/schemas/metadata.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Survey Metadata Schema",
    "description": "Survey Metadata Schema",
    "type": "object",
    "properties": {
        "survey_id": {
            "type": "string",
            "description": "Unique Survey ID"
        },
        "language": {
            "type": "string",
            "description": "Language of the survey",
            "enum": [
                "EN",
                "CH",
                "FR"
            ]
        },
        "short_name": {
            "type": "string",
            "description": "Short name of survey (for buttons)"
        },
        "full_name": {
            "type": "string",
            "description": "Full name of survey"
        },
        "description": {
            "type": "string",
            "description": "Description of survey"
        },
        "survey_type": {
            "type": "string",
            "description": "Type of survey",
            "enum": [
                "physical",
                "psychological",
                "physiological",
                "other"
            ]
        },
        "display": {
            "type": "boolean",
            "description": "Whether or not to display this survey"
        },
        "is_data_collection": {
            "type": "boolean",
            "description": "Is this a data collection survey"
        },
        "turn_off_data_collection": {
            "type": "boolean",
            "description": "Turn off data collection"
        },
        "has_results": {
            "type": "boolean",
            "description": "Does the survey calculate results"
        },
        "is_machine_learning": {
            "type": "boolean",
            "description": "Does this survey use a machine learning model to calculate results"
        },
        "instructions": {
            "type": "string",
            "description": "Survey instructions (can be formatted in HTML)"
        }
    },
    "required": [
        "survey_id",
        "language",
        "short_name",
        "full_name",
        "description",
        "survey_type",
        "display",
        "is_data_collection",
        "turn_off_data_collection",
        "has_results",
        "is_machine_learning",
        "instructions"
    ],
    "additionalProperties": false
}

=== kang-lee-lab/lab-surveys/App/templates/json_templates/nafld_metadata.json
{
    "survey_id": "nafld",
    "language": "EN",
    "short_name": "Non-Alchoholic Fatty Liver Disease (NAFLD)",
    "full_name": "Non-Alchoholic Fatty Liver Disease (NAFLD) prediction interactive webpage",
    "description": "This applet computes an individuals likelihood of NAFLD. Based on 20 physical measures and blood biomarkers, this app uses a machine learning model to compute the likelihood of NAFLD.\n\nNon-alcoholic fatty liver disease (NAFLD) is becoming a major global burden of disease, but its diagnosis based on liver biopsy is invasive and expensive. This study aimed to investigate the feasibility of using patient physical and blood biomarkers to build computational models to predict NAFLD risks accurately.\nWe obtained a large dataset (N=120,376) containing patients’ physical and blood measurements, and their NAFLD status based on the invasive liver biopsy. Using this dataset, the most important patient physical and blood biomarkers were extracted using feature selection techniques. Then, using the most important features, six different machine learning algorithms trained and tested models that predict the NAFLD status. Finally, these models were validated with a pristine set of patient data never used in model training and testing, and SHAP (SHapley Additive exPlanations) analysis was performed on the final model.\nWe identified the top 20 features for predicting NAFLD risk including Weight, BMI, Alanine aminotransferase, and HDL Cholesterol. Our best machine learning model using the Extreme Gradient Boosting Decision Tree (XGB) technique achieved 84.94% area under the curve (ROC AUC), and 82.58% accuracy (88.75% sensitivity and 81.13% specificity) for predicting NAFLD status\nOur findings suggest that machine learning models based on patient physical and blood biomarkers provide a viable, non-invasive, and inexpensive method to assess patients’ risks for non-alcoholic fatty liver disease accurately.",
    "survey_type": "physiological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": true,
    "instructions": "Please enter your answers below:"
}

=== kang-lee-lab/lab-surveys/App/templates/childbmi_metadata.json
{
    "survey_id": "childbmi",
    "language": "EN",
    "short_name": "Children's Future BMI prediction",
    "full_name": "Children's Future BMI prediction interactive webpage",
    "description": "This applet computes children's future height, weight, and BMI. Based on a child's current age and physical measurements, this app uses a machine learning model to compute the children's future height, weight, and BMI for a specified number of years into the future.\n\nYasin, Y., Sun, Y.H., and Lee, K. (2022). A machine learning approach for predicting children's future BMI. Canadian Developmental Psychology Conference.",
    "survey_type": "physiological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": false,
    "instructions": "Please answer the following questions:"
}

=== kang-lee-lab/lab-surveys/App/templates/json_templates/ihrv_metadata.json
{
    "survey_id": "ihrv",
    "language": "EN",
    "short_name": "integrated Heart Rate Variability (iHRV)",
    "full_name": "integrated Heart Rate Variability (iHRV) calculator",
    "description": "The integrated Heart Rate Variability (iHRV) synthesizes results of 29 Heart Rate Variability (HRV) measures (see description for each measure in the table below) into a set of six indexes, one for each orthogonal dimension that underly HRV measures (HRV-D1-6), which are then combined to produce a single integrated index (iHRV). HRV measures assess variation in the time intervals between two successive heartbeats. These measures can be obtained through analysis of an electrocardiogram. Extensive research has found these measures to be indicative of a person’s heart health. However, different measures are often used across research, clinical, and commercial domains, making interpretation of HRV difficult. Wu et al. (submitted) established a method for integrating multiple measures to enable examination of a small set of indexes that reflect the six dimensions of HRV, called Heart Rate Variability of dimensions 1 to 6 (HRV-D1-6). As well, a single index called integrated Heart Rate Variability (iHRV) is derived to allow easy interpretation. Here, we provide the iHRV Calculator for you to try Wu et al. (submitted)’s method! Please input values of HRV measures and we will generate your HRV-D1-6 and iHRV!",
    "survey_type": "psychological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": false,
    "instructions": "Please enter your answers below:"
}

=== kang-lee-lab/lab-surveys/App/static/surveys_files/dass/metadata_EN.json
{
    "survey_id": "dass",
    "language": "EN",
    "short_name": "Depression Anxiety Stress Scales (DASS) prediction",
    "full_name": "Depression Anxiety Stress Scales (DASS) prediction interactive webpage",
    "description": "This applet computes an individual's likelihood of moderate anxiety, depression or stress. Based on 6 questions, this app uses a machine learning model to compute the likelihood of anxiety, depression or stress.",
    "survey_type": "psychological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": true,
    "instructions": "Please enter your answers below:"
}

=== kang-lee-lab/lab-surveys/App/templates/json_templates/mmpi_metadata.json
{
    "survey_id": "mmpi",
    "language": "EN",
    "short_name": "Minnesota Multiphasic Personality Inventory (MMPI) prediction",
    "full_name": "Minnesota Multiphasic Personality Inventory (MMPI) prediction interactive webpage",
    "description": "This applet computes an individuals likelihood of MMPI. Based on 100 questions, this app uses a machine learning model to compute the likelihood of MMP\n\nMinnesota Multiphasic Personality Inventory (MMPI) is the most widely used psychometric test in the world. This study aimed to investigate the feasibility of using a reduced number of questions to predict the status in each conditions accurately.\nWe obtained a dataset of MMPI-2 responses from the Beijing Anding Hospital. The original dataset contains anonymized information on the participants including their demographics (age, sex, etc.), the raw scores and T-scores to each of the conditions, and the answers to each of the questions from the MMPI-2 test from each participant. The information of the participants includes their serial number, age, and their lname. The responses to the questions are “Yes”, “No”, or “Maybe”.\nWe identified the top 100 questions for predicting the ten MMPI conditions, which achieved at least 85% area under curve (AUC ROC) for predicting each of the conditions.\nOur findings suggest that machine learning models using reduced number of questions are capable of making accurate assessment for MMPI.",
    "survey_type": "psychological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": true,
    "instructions": "Please enter your answers below:"
}

=== kang-lee-lab/lab-surveys/backend/surveys/static/survey_files/asq/metadata_EN.json
{
    "survey_id": "asq",
    "language": "EN",
    "short_name": "Average Stress Quotient (ASQ)",
    "full_name": "Average Stress Quotient (ASQ) calculator",
    "description": "The Average Stress Quotient (ASQ) is a synthesized value derived from 29 Heart Rate Variability (HRV) indexes . HRV indexes are measures of variation in the time intervals between two successive heartbeats. These measures can be obtained through analysis of electrocardiography. Extensive research has found these measures to be indicative of a person\u2019s stress level. However, research often use different indexes, making interpretation of HRV as a physiological indicator of stress difficult. Wu et al. (2026) established a method for synthesizing multiple indexes to enable examination of six dimensions of HRV, and further compute scores that can be used to easily interpret the dimensions in terms of stress levels. Specifically, we provide Stress Quotient 1-6 (SQ1-6) to interpret stress levels based on each of the 6 dimensions of HRV, and an Average Stress Quotient (ASQ) for wholistic interpretation of stress based on the 29 HRV indexes. Here, we provide the ASQ Calculator for you to try Wu et al. (2026)\u2019s method! Please input values of HRV indexes and we will generate your SQ1-6 and ASQ!",
    "survey_type": "psychological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": false,
    "instructions": "Please enter your answers below:"
}

=== kang-lee-lab/lab-surveys/App/static/surveys/sample_survey/metadata_EN.json
{
    "survey_id": "sample_survey",
    "language": "EN",
    "short_name": "Sample Survey",
    "full_name": "Sample survey for demonstration purposes",
    "description": "Sample survey for demonstration purposes",
    "survey_type": "other",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": false,
    "instructions": "Please answer the following questions:"
}

=== kang-lee-lab/lab-surveys/backend/surveys/static/survey_files/dass_multiclass/metadata_EN.json
{
    "survey_id": "dass_multiclass",
    "language": "EN",
    "short_name": "Depression Anxiety Stress Scales (DASS) multiclass anxiety prediction",
    "full_name": "Depression Anxiety Stress Scales (DASS) multiclass anxiety prediction interactive webpage",
    "description": "This applet computes an individual's anxiety classification using a machine learning model. Please read each statement and indicate how much the statement applied to you over the past week.",
    "survey_type": "psychological",
    "display": false,
    "is_data_collection": false,
    "turn_off_data_collection": true,
    "has_results": true,
    "is_machine_learning": true,
    "instructions": "Please enter your answers below:"
}
