=== kang-lee-lab/lab-surveys/App/static/schemas/results.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "title": "Survey Results Schema",
    "description": "Survey Results Response Schema",
    "type": "object",
    "properties": {
        "survey_id": {
            "type": "string",
            "description": "Unique Survey ID"
        },
        "language": {
            "type": "string",
            "description": "Language of the survey",
            "enum": ["EN", "CH", "FR"]
        },
        "results": {
            "type": "array",
            "description": "List of result fields and values. Can be an empty list if no survey results are to be returned.",
            "items": {
                "type": "object",
                "properties": {
                    "result_id": {
                        "type": "string",
                        "description": "Result ID"
                    },
                    "result_name": {
                        "type": "string",
                        "description": "Result name"
                    },
                    "result_text": {
                        "type": "string",
                        "description": "Text description of the result"
                    },
                    "result": {
                        "type": "object",
                        "description": "Contents of the result",
                        "oneOf": [
                            {
                                "type": "object",
                                "description": "Scalar result",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "value": "scalar"
                                    },
                                    "value": {
                                        "type": "number",
                                        "description": "Result value as a number"
                                    },
                                    "unit": {
                                        "type": "string",
                                        "description": "Result unit"
                                    },
                                    "result_explanation": {
                                        "type": "string",
                                        "description": "Result explanation in text"
                                    },
                                    "value_range_min": {
                                        "type": "number",
                                        "description": "Lower bound of the value (95% CI)"
                                    },
                                    "value_range_max": {
                                        "type": "number",
                                        "description": "Upper bound of the value (95% CI)"
                                    },
                                    "value_lower_bound": {
                                        "type": "number",
                                        "description": "Lower bound of the value"
                                    },
                                    "value_upper_bound": {
                                        "type": "number",
                                        "description": "Upper bound of the value"
                                    },
                                    "is_reverse_order": {
                                        "type": "boolean",
                                        "description": "Whether the value is reversed with severity, i.e. 0 is the best, 100 is the worst. Normal order is where 0 is the worst, 100 is the best."
                                    },
                                    "use_dial": {
                                        "type": "boolean",
                                        "description": "Whether or not to display results on a dial"
                                    }
                                },
                                "required": [
                                    "type",
                                    "value",
                                    "unit",
                                    "value_lower_bound",
                                    "value_upper_bound",
                                    "is_reverse_order",
                                    "use_dial"
                                ],
                                "additionalProperties": false
                            },
                            { 
                                "type": "object", 
                                "description": "Percentage result",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "value": "percentage"
                                    },
                                    "value": {
                                        "type": "number",
                                        "description": "Result value as a number"
                                    },
                                    "result_explanation": {
                                        "type": "string",
                                        "description": "Result explanation in text"
                                    },
                                    "value_range_min": {
                                        "type": "number",
                                        "description": "Lower bound of the value (95% CI)"
                                    },
                                    "value_range_max": {
                                        "type": "number",
                                        "description": "Upper bound of the value (95% CI)"
                                    },
                                    "is_reverse_order": {
                                        "type": "boolean",
                                        "description": "Whether the value is reversed with severity, i.e. 0 is the best, 100 is the worst. Normal order is where 0 is the worst, 100 is the best."
                                    },
                                    "use_dial": {
                                        "type": "boolean",
                                        "description": "Whether or not to display results on a dial"
                                    }
                                },
                                "required": [
                                    "type",
                                    "value",
                                    "is_reverse_order",
                                    "use_dial"
                                ],
                                "additionalProperties": false
                            },
                            { 
                                "type": "object", 
                                "description": "Text result",
                                "properties": {
                                    "type": {
                                        "type": "string",
                                        "value": "text"
                                    },
                                    "value": {
                                        "type": "string",
                                        "description": "Result text"
                                    }
                                },
                                "required": [
                                    "type",
                                    "value"
                                ],
                                "additionalProperties": false
                            }
                        ]
                    }
                },
                "required": [
                    "result_id",
                    "result_name",
                    "result_text",
                    "result"
                ],
                "additionalProperties": false
            }
        },
        "use_multiedged_graph": {
            "type": "boolean",
            "description": "Whether or not to display results on a multiedged graph"
        },
        "use_table": {
            "type": "boolean",
            "description": "Whether or not to display results in a table"
        },
        "final_message": {
            "type": "string",
            "description": "Final message after the result (can be HTML formatted)"
        }
    },
    "required": [
        "survey_id",
        "language",
        "results",
        "use_multiedged_graph",
        "use_table",
        "final_message"
    ],
    "additionalProperties": false
}

=== kang-lee-lab/lab-surveys/App/static/surveys/sample_survey/results_EN.json
{
    "survey_id": "sample_survey",
    "language": "EN",
    "results": [
        {
            "result_id": "score1",
            "result_name": "Scalar Score",
            "result_text": "This score represents a scalar",
            "result": {
                "type": "scalar",
                "value": 10,
                "unit": "m",
                "value_lower_bound": 0,
                "value_upper_bound": 1000,
                "is_reverse_order": false,
                "use_dial": false
            }
        },
        {
            "result_id": "score2",
            "result_name": "Likelihood Score",
            "result_text": "This score represents a percentage value",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of xxx",
                "is_reverse_order": true,
                "use_dial": true
            }
        },
        {
            "result_id": "score3",
            "result_name": "Text Output",
            "result_text": "This output represents a text description",
            "result": {
                "type": "text",
                "value": "blah blah blah"
            }
        }
    ],
    "use_multiedged_graph": false,
    "use_table": true,
    "final_message": "This survey result is unofficial and does not represent medical advice. Please seek professional for an official diagnosis."
}

=== kang-lee-lab/lab-surveys/App/templates/json_templates/ihrv_results.json
{
    "survey_id": "ihrv",
    "language": "EN",
    "results": [
        {
            "result_id": "ihrv",
            "result_name": "iHRV",
            "result_text": "This score represents your iHRV score",
            "result": {
                "type": "scalar",
                "value": 10,
                "unit": "m",
                "value_lower_bound": 0,
                "value_upper_bound": 1000,
                "is_reverse_order": false,
                "use_dial": false
            }
        },
        {
            "result_id": "underlying_ihrv",
            "result_name": "Underlying iHRV Measures",
            "result_text": "This output represents the degree of your iHRV from extremely high to extremely low",
            "result": {
                "type": "text",
                "value": ""
            }
        },
        {
            "result_id": "ihrv_classification",
            "result_name": "iHRV Classification",
            "result_text": "This output represents what color your iHRV appears as on the graph",
            "result": {
                "type": "text",
                "value": ""
            }
        }
    ],
    "use_multiedged_graph": true,
    "use_table": false,
    "final_message": "Lower HRV measures are related to higher risk of cardiovascular disease. If your iHRV fell within ranges classified as shades of green, it signals good heart health. If your iHRV fell within ranges classified as yellow, orange, or red, you may wish to examine your HRV measures further. Please consult a medical professional with any health concerns. Your iHRV is reflect multiple underlying HRV measures. The table below can be used to interpret your score.\nDisplayed below are your Heart Rate Variability of dimensions 1-6 (HRV-D1-6). Each reflect an orthogonal dimension underlying your HRV measures.\n\n*This webpage does not contain medical/health advice. This tool is intended for informational and educational purposes only, and should not be taken as a substitute for professional advice. Reliance on any information on the webpage is solely at your own risk."
}

=== kang-lee-lab/lab-surveys/backend/surveys/static/survey_files/asq/results_EN.json
{
    "survey_id": "asq",
    "language": "EN",
    "results": [
        {
            "result_id": "asq",
            "result_name": "ASQ",
            "result_text": "This score represents your Average Stress Quotient (ASQ)",
            "result": {
                "type": "scalar",
                "value": 10,
                "unit": "m",
                "value_lower_bound": 0,
                "value_upper_bound": 1000,
                "is_reverse_order": false,
                "use_dial": false
            }
        },
        {
            "result_id": "underlying_sq",
            "result_name": "Underlying SQ Measures",
            "result_text": "This output represents your Stress Quotients for factors 1-6 (SQ1-6)",
            "result": {
                "type": "text",
                "value": ""
            }
        },
        {
            "result_id": "asq_classification",
            "result_name": "ASQ Classification",
            "result_text": "This output represents your ASQ stress level classification",
            "result": {
                "type": "text",
                "value": ""
            }
        }
    ],
    "use_multiedged_graph": true,
    "use_table": false,
    "final_message": "Your ASQ is an indication of your overall stress level. The table below can be used to interpret your score.\n\nASQ Range | ASQ Classification\n80 and over | Very High Stress\n70-79 | High Stress\n60-69 | Slightly High Stress\n41-59 | Average\n31-40 | Slightly Low Stress\n21-30 | Low Stress\n20 and below | Very Low Stress\n\nDisplayed below are your Stress Quotients for factors 1-6 (SQ1-6). Each SQ is unique and contribute to your overall Average Stress Quotient (ASQ).\n\n*This webpage does not contain medical/health advice. This tool is intended for informational and educational purposes only, and should not be taken as a substitute for professional advice. Reliance on any information on the webpage is solely at your own risk."
}

=== kang-lee-lab/lab-surveys/App/static/surveys_files/dass/results_EN.json
{
    "survey_id": "dass",
    "language": "EN",
    "results": [
        {
            "result_id": "anxiety_likelihood",
            "result_name": "Likelihood of Moderate Anxiety",
            "result_text": "This score represents a percentage value of the likelihood of moderate anxiety",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "Your likelihood of moderate anxiety is xxx",
                "is_reverse_order": true,
                "use_dial": true
            }
        },
        {
            "result_id": "depression_likelihood",
            "result_name": "Likelihood of Moderate Depression",
            "result_text": "This score represents a percentage value of the likelihood of moderate depression",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "Your likelihood of moderate depression is xxx",
                "is_reverse_order": true,
                "use_dial": true
            }
        },
        {
            "result_id": "stress_likelihood",
            "result_name": "Likelihood of Moderate Stress",
            "result_text": "This score represents a percentage value of the likelihood of moderate stress",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "Your likelihood of moderate stress is xxx",
                "is_reverse_order": true,
                "use_dial": true
            }
        }
    ],
    "use_multiedged_graph": true,
    "use_table": false,
    "final_message": "Displayed is your estimated likelihood of moderate anxiety, depression or stress given your answers to the DASS questions. This is calculated through a machine learning model trained using data collected from an online survey.\n\n*This webpage does not contain medical/health advice. This tool is intended for informational and educational purposes only, and should not be taken as a substitute for professional advice. Reliance on any information on the webpage is solely at your own risk."
}

=== kang-lee-lab/lab-surveys/backend/surveys/static/survey_files/sample_survey/results_EN.json
{
    "survey_id": "sample_survey",
    "language": "EN",
    "results": [
        {
            "result_id": "score1",
            "result_name": "Scalar Score",
            "result_text": "Sum of the two numbers you entered",
            "result": {
                "type": "scalar",
                "value": 10,
                "unit": "",
                "value_lower_bound": 0,
                "value_upper_bound": 200,
                "is_reverse_order": false,
                "use_dial": false
            }
        },
        {
            "result_id": "score2",
            "result_name": "Likelihood Score",
            "result_text": "Your experience rating as a percentage",
            "result": {
                "type": "percentage",
                "value": 10,
                "is_reverse_order": true,
                "use_dial": true
            }
        },
        {
            "result_id": "score3",
            "result_name": "Text Output",
            "result_text": "A short summary of your inputs",
            "result": {
                "type": "text",
                "value": ""
            }
        }
    ],
    "use_multiedged_graph": false,
    "use_table": true,
    "final_message": "This survey result is unofficial and does not represent medical advice. Please seek a professional for an official diagnosis."
}

=== kang-lee-lab/lab-surveys/backend/surveys/static/survey_files/mmpi/results_EN.json
{
    "survey_id": "mmpi",
    "language": "EN",
    "results": [
        {
            "result_id": "hypochondriasis",
            "result_name": "Likelihood of Hypochondriasis (Hs)",
            "result_text": "This score represents the likelihood of Hypochondriasis as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Hypochondriasis",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "depression",
            "result_name": "Likelihood of Depression (D)",
            "result_text": "This score represents the likelihood of Depression as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Depression",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "hysteria",
            "result_name": "Likelihood of Hysteria (Hy)",
            "result_text": "This score represents the likelihood of Hysteria as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Hysteria",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "psychopathic_deviate",
            "result_name": "Likelihood of Psychopathic Deviate (Pd)",
            "result_text": "This score represents the likelihood of Psychopathic Deviate as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Psychopathic Deviation",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "masculinity_femininity",
            "result_name": "Likelihood of Masculinity (MF)",
            "result_text": "This score represents the likelihood of being masculine as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Masculinity",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "paranoia",
            "result_name": "Likelihood of Paranoia (Pa)",
            "result_text": "This score represents the likelihood of Paranoia as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Paranoia",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "psychasthenia",
            "result_name": "Likelihood of Psychasthenia (Pt)",
            "result_text": "This score represents the likelihood of Psychasthenia as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Psychasthenia",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "schizophrenia",
            "result_name": "Likelihood of Schizophrenia (Sc)",
            "result_text": "This score represents the likelihood of Schizophrenia as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Schizophrenia",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "hypomania",
            "result_name": "Likelihood of Hypomania (Ma)",
            "result_text": "This score represents the likelihood of Hypomania as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Hypomania",
                "is_reverse_order": false,
                "use_dial": true
            }
        },
        {
            "result_id": "introversion",
            "result_name": "Likelihood of Social Introversion (Si)",
            "result_text": "This score represents the likelihood of Social Introversion as measured by MMPI-100",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of Social Introversion",
                "is_reverse_order": false,
                "use_dial": true
            }
        }
    ],
    "use_multiedged_graph": true,
    "use_table": false,
    "final_message": "Displayed are the predicted likelihoods for the 10 measurements of MMPI. This is calculated through a machine learning model trained using patient data.\n\n*This webpage does not contain medical/health advice. This tool is intended for informational and educational purposes only, and should not be taken as a substitute for professional advice. Reliance on any information on the webpage is solely at your own risk."
}

=== kang-lee-lab/lab-surveys/App/templates/json_templates/childbmi_results.json
{
    "survey_id": "childbmi",
    "language": "EN",
    "results": [
        {
            "result_id": "age_to_predict",
            "result_name": "Age to predict",
            "result_text": "Age to predict future BMI at",
            "result": {
                "type": "scalar",
                "value": 10,
                "unit": "years",
                "value_lower_bound": 0,
                "value_upper_bound": 1000,
                "is_reverse_order": false,
                "use_dial": false
            }
        }
    ],
    "use_multiedged_graph": false,
    "use_table": false,
    "final_message": "Displayed is your children's future height, weight, and BMI given their current physical measurements. This is calculated through a machine learning model trained using patient data.\n\n*This webpage does not contain medical/health advice. This tool is intended for informational and educational purposes only, and should not be taken as a substitute for professional advice. Reliance on any information on the webpage is solely at your own risk."
}

=== kang-lee-lab/lab-surveys/App/static/surveys_files/nafld/results_EN.json
{
    "survey_id": "nafld",
    "language": "EN",
    "results": [
        {
            "result_id": "nafld_likelihood",
            "result_name": "Likelihood of NAFLD",
            "result_text": "This score represents a percentage value of the likelihood of having NAFLD",
            "result": {
                "type": "percentage",
                "value": 10,
                "result_explanation": "You have a high likelihood of xxx",
                "is_reverse_order": true,
                "use_dial": true
            }
        }
    ],
    "use_multiedged_graph": true,
    "use_table": false,
    "final_message": "Displayed is your estimated likelihood of Non-Alcoholic Fatty Liver Disease (NAFLD) given your physical measurements and blood biomarkers. This is calculated through a machine learning model trained using patient data.\n\n*This webpage does not contain medical/health advice. This tool is intended for informational and educational purposes only, and should not be taken as a substitute for professional advice. Reliance on any information on the webpage is solely at your own risk."
}
